# Basic
title: MSDM-5001
subtitle: My page of MSDM-5001
welcome_message: Welcome to Nengbo's page!
description: 嗨......................
creator: <a href="https://prog-crs.ust.hk/pgcourse/2019-20/MSDM">@MSDM-5001</a>

url: "https://prog-crs.ust.hk/pgcourse/2019-20/MSDM"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: GitHub,     in_site: false,  description: GcsSloop's GitHub,    url: 'https://prog-crs.ust.hk/pgcourse/2019-20/MSDM'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 GcsSloop,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: MSDM-5001
    # duoshuo:
# Social
social:
    weibo: 冰清玉洁车老师
    github: 甜美零号
    twitter: MSDM-5001
    
    mail: nhu@connect.ust.hk
    copyright: http://choosealicense.online

# Google Analytics
ga:
    id: UA-82493667-1
    host: https://prog-crs.ust.hk/pgcourse/2019-20/MSDM
